FROM resin/rpi-raspbian:jessie

RUN apt-get update && apt-get install -y --no-install-recommends \
  apt-utils wget unzip build-essential cmake pkg-config \
  libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev \
  libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
  libxvidcore-dev libx264-dev \
  libgtk2.0-dev libgtk-3-dev \
  libatlas-base-dev gfortran \
  python3-dev python3-pip python-pip python3-h5py \
  python3-numpy python3-matplotlib python3-scipy python3-pandas 

WORKDIR foocars

COPY . .


RUN pip3 install tensorflow
RUN pip3 install pipenv
RUN pip3 install mock


# Enable command line Arduino via platformio
RUN pip install platformio
# Enable pic32 compiler execution
RUN ln -s /lib/arm-linux-gnueabihf/ld-linux.so.3 /lib/ld-linux.so.3
RUN pio platform install microchippic32

# Enable and compile a default program
WORKDIR /foocars/arduino/MOTTOServoDataSampleDelay
RUN pio lib install 944
RUN pio run
RUN pio device list 

WORKDIR /foocars
RUN pip3 install -r requirements.txt


# TODO no longer run as service but as a car script ottoLogger.py for example
# Set up the raspberry pi services
WORKDIR /usr/local/bin
RUN ln -s /foocars/services/ottoMicroLogger.py
RUN ln -s /foocars/services/ottoMicroLogger.service
RUN systemctl enable /foocars/services/ottoMicroLogger.service

# TODO: Enable USB Flash drive code
# TODO: upload Arduino code to car

# TODO: add default weigths


RUN echo  "Done"
